---
apiVersion: v1
kind: Namespace
metadata:
  name: demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static-deployment
  namespace: demo
  labels:
    name: nginx-static
    #  annotations:
    #flux.weave.works/automated: true
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx-static
  template:
    metadata:
      labels:
        name: nginx-static
    spec:
      # automountServiceAccountToken: false
      containers:
      - name: nginx-static
        image: 220411221176.dkr.ecr.us-east-1.amazonaws.com/demo1:hello-world.v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
