---
apiVersion: v1
kind: Service
metadata:
  name: nginx-static-lb
  namespace: playground
  labels:
    name: nginx-static
spec:
  type: LoadBalancer
  selector:
    name: nginx-static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
